name: C/C++ CI

on: [push]
env: 
  BUILD_TYPE: Debug

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
