name: C/C++ CI

on: [push]
env: 
  BUILD_TYPE: Debug

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install gtest
      run: |
        wget https://github.com/google/googletest/archive/master.zip
        unzip master.zip
        mv googletest-master /googletest
        mkdir -p /googletest/build
        cd /googletest/build
        cmake ..
        make
        make install
        cd /
        export GTEST_DIR="/googletest/googletest/" GTEST_LIB_DIR="/googletest/build/lib/"
    - name: prepare
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
