name: C/C++ CI

on: [push]
env: 
  BUILD_TYPE: Debug

jobs:
  build:
    
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install GTest
      run: |
        wget https://github.com/google/googletest/archive/master.zip
        unzip master.zip
        mv googletest-master ${{runner.workspace}}/googletest
        mkdir -p ${{runner.workspace}}/googletest/build
        cd ${{runner.workspace}}/googletest/build
        cmake ..
        make
        sudo make install
        cd ${{runner.workspace}}
        export GTEST_DIR="${{runner.workspace}}/googletest/googletest/" GTEST_LIB_DIR="${{runner.workspace}}/googletest/build/lib/"
    - name: Prepare Workspace
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
